In [1]:
import pandas as pd
import plotly.express as px

In [5]:
df_agencias = pd.read_excel('../../Data/Raw/agencias.xlsx', skiprows=9)

In [6]:
df_agencias.head()

,CNPJ,SEQUENCIAL DO CNPJ,DV DO CNPJ,NOME INSTITUIÇÃO,SEGMENTO,CÓD COMPE AG,NOME AGÊNCIA,ENDEREÇO,NÚMERO,COMPLEMENTO,BAIRRO,CEP,MUNICíPIO,UF,DATA INÍCIO,DDD,FONE,ID INSTALAÇÃO,ID INSTALAÇÃO ESTBAN,MUNICIPIO IBGE
0,00.000.000,2.0,72.0,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,2.0,MANAUS ...,"R.GUILHERME MOREIRA,315",,"SUBLOJA,LOJA E 2.ANDAR ...",CENTRO,69005-300,MANAUS ...,AM,1908-01-14 00:00:00,92.0,36215500.0,9.999994e+09,A9994472,1302603.0
1,00.000.000,3.0,53.0,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,3.0,PRESIDENTE VARGAS ...,"AV.PRES.VARGAS,248",,1.E 2.ANDARES ...,CAMPINA,66010-900,BELEM ...,PA,1908-07-01 00:00:00,91.0,32164888.0,9.999994e+09,A9994471,1501402.0
2,00.000.000,4.0,34.0,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,4.0,SANTOS ...,"R.QUINZE DE NOVEMBRO,195",,...,CENTRO,11010-908,SANTOS ...,SP,1908-08-22 00:00:00,13.0,40097406.0,9.999994e+09,A9994470,3548500.0
3,00.000.000,5.0,15.0,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,5.0,CAMPOS GOYTACAZES ...,RUA QUARTA DA JORNADA,11,PRACA DAS 04 JORNADAS ...,CENTRO,28010-510,CAMPOS DOS GOYTACAZES ...,RJ,1910-06-26 00:00:00,22.0,27370405.0,9.999994e+09,A9994469,3301009.0
4,00.000.000,6.0,4.0,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,6.0,SALVADOR ...,"SEXTA AVENIDA,600",,SECRETARIA DA EDUCACAO-TERREO ...,CAB,41745-002,SALVADOR ...,BA,1910-07-15 00:00:00,71.0,33628803.0,9.999994e+09,A9994468,2927408.0

In [7]:
df_agencias.columns

Index(['CNPJ      ', 'SEQUENCIAL DO CNPJ', 'DV DO CNPJ',
       'NOME INSTITUIÇÃO                                                                                                                                                                                        ',
       'SEGMENTO                                                    ',
       'CÓD COMPE AG',
       'NOME AGÊNCIA                                                ',
       'ENDEREÇO                                ', 'NÚMERO    ',
       'COMPLEMENTO                                       ',
       'BAIRRO                        ', 'CEP      ',
       'MUNICíPIO                                                   ', 'UF',
       'DATA INÍCIO', 'DDD  ', 'FONE       ', 'ID INSTALAÇÃO',
       'ID INSTALAÇÃO ESTBAN', 'MUNICIPIO IBGE'],
      dtype='object')

In [ ]:
df_agencias.columns = df_agencias.columns.str.strip()

In [26]:
df_agencias = df_agencias.rename(columns={
    'NOME INSTITUIÇÃO': 'nome_instituicao',
    'NOME AGÊNCIA': 'nome_agencia',
    'ENDEREÇO': 'endereco',
    'NÚMERO': 'numero',
    'COMPLEMENTO': 'complemento',
    'BAIRRO': 'bairro',
    'CEP': 'cep',
    'MUNICíPIO': 'municipio',
    'MUNICIPIO IBGE': 'municipio_ibge'
})

In [27]:
colunas_desejadas = [
    'nome_instituicao',
    'nome_agencia',
    'endereco',
    'numero',
    'complemento',
    'bairro',
    'cep',
    'municipio',
    'municipio_ibge'
]

In [46]:
df_limpo = df_agencias[colunas_desejadas]

In [48]:

df_limpo.head()

,nome_instituicao,nome_agencia,endereco,numero,complemento,bairro,cep,municipio,municipio_ibge
0,BANCO DO BRASIL S.A.,MANAUS,"R.GUILHERME MOREIRA,315",,"SUBLOJA,LOJA E 2.ANDAR",CENTRO,69005-300,MANAUS,1302603.0
1,BANCO DO BRASIL S.A.,PRESIDENTE VARGAS,"AV.PRES.VARGAS,248",,1.E 2.ANDARES,CAMPINA,66010-900,BELEM,1501402.0
2,BANCO DO BRASIL S.A.,SANTOS,"R.QUINZE DE NOVEMBRO,195",,,CENTRO,11010-908,SANTOS,3548500.0
3,BANCO DO BRASIL S.A.,CAMPOS GOYTACAZES,RUA QUARTA DA JORNADA,11,PRACA DAS 04 JORNADAS,CENTRO,28010-510,CAMPOS DOS GOYTACAZES,3301009.0
4,BANCO DO BRASIL S.A.,SALVADOR,"SEXTA AVENIDA,600",,SECRETARIA DA EDUCACAO-TERREO,CAB,41745-002,SALVADOR,2927408.0

In [49]:
df_limpo.to_csv('../../Data/Processed/agencias_tratado.csv')